version: '3.1'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d/
      - ./app/YtManagerApp/static:/www/static
      - ./data/media:/www/media
    ports:
      - "80:80"
    depends_on:
      - web

  web:
    build: .
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./data:/usr/src/ytsm/data
      - ./downloads:/usr/src/ytsm/downloads